theme: minima
markdown: kramdown

title: |-
    Self-Contained Calibration of an Elastic Humanoid Upper Body 
    Using Only a Head-Mounted RGB Camera

author: johannes.tenhumberg@dlr.de

header_pages:
  - _pages/robot.md
  - _pages/camera.md
  - _pages/methods.md
  - _pages/results.md
  - _pages/dataset.md

include:
    - _pages
    
exclude: 
    - .gitignore
    - Gemfile
    - README.md
